fix: introduction of sigpipe checks broke windows compatibility (#144)
PR #127 made important fixes for Unix. But I forgot to take into account
that the SIGPIPE signal does not exist on Windows. More problematically,
the signal module in Python for Windows doesn't have a SIGPIPE property.
Windows users saw this error:

> module 'signal' has no attribute 'SIGPIPE'

This change accounts for the missing property, and should hopefully get
git-format-staged working on Windows again.